#!/usr/bin/env bash
# prepare-reinstall.sh - Prepare system reinstall script
# Generates automated reinstall script with all configurations

set -Eeuo pipefail

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TOOLKIT_ROOT="$(dirname "$SCRIPT_DIR")"

# Load common functions
source "$TOOLKIT_ROOT/utils/common.sh"
source "$TOOLKIT_ROOT/utils/i18n.sh"

# Output script file
REINSTALL_SCRIPT="${REINSTALL_SCRIPT:-$HOME/reinstall-system-$(date +%Y%m%d_%H%M%S).sh}"

# Collect system information
collect_system_info() {
    i18n_info "detect_os"
    
    local os_id os_version arch
    os_id=$(get_system_info "os")
    os_version=$(get_system_info "version")
    arch=$(get_system_info "arch")
    
    echo "os_id='$os_id'"
    echo "os_version='$os_version'"
    echo "arch='$arch'"
}

# Collect network information
collect_network_info() {
    i18n_info "detect_network"
    
    local primary_interface primary_ip
    primary_interface=$(get_primary_interface)
    primary_ip=$(get_primary_ip)
    
    # Get all IP addresses
    local all_ipv4=()
    if has_cmd ip; then
        while IFS= read -r ip; do
            [[ -n "$ip" ]] && all_ipv4+=("$ip")
        done < <(ip -4 addr show | grep -oP 'inet \K[\d.]+' | grep -v '^127\.')
    fi
    
    echo "primary_interface='$primary_interface'"
    echo "primary_ip='$primary_ip'"
    echo "all_ipv4='${all_ipv4[*]}'"
}

# Generate reinstall script
generate_reinstall_script() {
    i18n_info "generating_script"
    
    # Collect information
    local sys_info net_info
    sys_info=$(collect_system_info)
    net_info=$(collect_network_info)
    
    eval "$sys_info"
    eval "$net_info"
    
    # Create reinstall script
    cat > "$REINSTALL_SCRIPT" << 'REINSTALL_EOF'
#!/usr/bin/env bash
# Automated System Reinstall Script
# Generated by Server Toolkit

set -Eeuo pipefail

# Color codes
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

print_info() { echo -e "${BLUE}[INFO]${NC} $1"; }
print_success() { echo -e "${GREEN}[SUCCESS]${NC} $1"; }
print_warning() { echo -e "${YELLOW}[WARNING]${NC} $1"; }
print_error() { echo -e "${RED}[ERROR]${NC} $1"; }

# System information
REINSTALL_EOF

    # Add collected information
    cat >> "$REINSTALL_SCRIPT" << REINSTALL_EOF
OS_ID="$os_id"
OS_VERSION="$os_version"
ARCH="$arch"
PRIMARY_INTERFACE="$primary_interface"
PRIMARY_IP="$primary_ip"

REINSTALL_EOF

    # Add reinstall instructions
    cat >> "$REINSTALL_SCRIPT" << 'REINSTALL_EOF'

# Display system information
display_system_info() {
    echo ""
    echo "=========================================="
    echo "  System Reinstall Information"
    echo "=========================================="
    echo ""
    echo "Operating System: $OS_ID $OS_VERSION"
    echo "Architecture: $ARCH"
    echo "Primary Interface: $PRIMARY_INTERFACE"
    echo "Primary IP: $PRIMARY_IP"
    echo ""
}

# Confirm reinstall
confirm_reinstall() {
    echo ""
    print_warning "WARNING: This will reinstall the operating system!"
    print_warning "All data on the system disk will be LOST!"
    echo ""
    
    read -r -p "Are you sure you want to continue? [y/N] " response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        print_info "Reinstall cancelled"
        exit 0
    fi
    
    echo ""
    read -r -p "Type 'REINSTALL' to confirm: " confirm
    if [[ "$confirm" != "REINSTALL" ]]; then
        print_error "Confirmation failed"
        exit 1
    fi
}

# Prepare reinstall
prepare_reinstall() {
    print_info "Preparing system reinstall..."
    
    # Check if running as root
    if [[ "$(id -u)" -ne 0 ]]; then
        print_error "This script must be run as root"
        exit 1
    fi
    
    # Check network connectivity
    if ! ping -c 1 8.8.8.8 >/dev/null 2>&1; then
        print_error "No network connectivity"
        exit 1
    fi
    
    print_success "Preparation complete"
}

# Download reinstall tool
download_reinstall_tool() {
    print_info "Downloading reinstall tool..."
    
    # Using bin456789/reinstall
    local reinstall_url="https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh"
    
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$reinstall_url" -o /tmp/reinstall.sh
    elif command -v wget >/dev/null 2>&1; then
        wget -q "$reinstall_url" -O /tmp/reinstall.sh
    else
        print_error "Neither curl nor wget is available"
        exit 1
    fi
    
    chmod +x /tmp/reinstall.sh
    print_success "Reinstall tool downloaded"
}

# Execute reinstall
execute_reinstall() {
    print_info "Starting system reinstall..."
    
    # Customize reinstall parameters here
    # Example: bash /tmp/reinstall.sh debian 12
    
    print_warning "Please customize the reinstall command in this script"
    print_info "Example: bash /tmp/reinstall.sh debian 12"
    print_info "See: https://github.com/bin456789/reinstall"
    
    # Uncomment and customize the following line:
    # bash /tmp/reinstall.sh debian 12
}

# Main function
main() {
    display_system_info
    confirm_reinstall
    prepare_reinstall
    download_reinstall_tool
    
    echo ""
    print_info "Reinstall tool is ready at: /tmp/reinstall.sh"
    print_info "Please customize the reinstall command in this script"
    print_info "Then run: bash $0"
    echo ""
    
    # Uncomment to execute reinstall automatically:
    # execute_reinstall
}

main "$@"
REINSTALL_EOF

    chmod +x "$REINSTALL_SCRIPT"
    i18n_success "script_generated"
}

# Create reinstall guide
create_reinstall_guide() {
    local guide_file="${REINSTALL_SCRIPT%.sh}-GUIDE.txt"
    
    {
        echo "=== System Reinstall Guide ==="
        echo "Generated: $(date)"
        echo ""
        echo "=== Reinstall Script ==="
        echo "Location: $REINSTALL_SCRIPT"
        echo ""
        echo "=== Before Reinstall ==="
        echo "1. Backup all important data"
        echo "2. Save network configuration"
        echo "3. Note down all service configurations"
        echo "4. Backup SSH keys and authorized_keys"
        echo "5. Document all installed software"
        echo ""
        echo "=== Reinstall Steps ==="
        echo "1. Review and customize the reinstall script"
        echo "2. Edit the OS and version in the script"
        echo "3. Run: bash $REINSTALL_SCRIPT"
        echo "4. Wait for the reinstall to complete"
        echo "5. System will reboot automatically"
        echo ""
        echo "=== After Reinstall ==="
        echo "1. Login to the new system"
        echo "2. Run server-toolkit post-reinstall tools"
        echo "3. Restore configurations from backup"
        echo "4. Reinstall required software"
        echo "5. Verify all services are working"
        echo ""
        echo "=== Post-Reinstall Tools ==="
        echo "Use server-toolkit to configure the new system:"
        echo ""
        echo "# Download server-toolkit"
        echo "curl -fsSL https://raw.githubusercontent.com/k3s-forge/server-toolkit/main/bootstrap.sh | bash"
        echo ""
        echo "# Or run individual tools:"
        echo "- setup-ip.sh: Configure IP addresses"
        echo "- setup-hostname.sh: Configure hostname"
        echo "- setup-dns.sh: Configure DNS"
        echo "- setup-tailscale.sh: Setup Tailscale"
        echo "- optimize-network.sh: Optimize network"
        echo "- optimize-system.sh: Optimize system"
        echo ""
        echo "=== Important Notes ==="
        echo "- Keep this guide and the reinstall script safe"
        echo "- Test the reinstall process in a non-production environment first"
        echo "- Have a backup plan in case something goes wrong"
        echo "- Keep access to the server console (IPMI/KVM)"
        echo ""
        echo "=== Support ==="
        echo "- Documentation: https://github.com/k3s-forge/server-toolkit"
        echo "- Issues: https://github.com/k3s-forge/server-toolkit/issues"
        echo ""
    } > "$guide_file"
    
    i18n_info "report_saved" "$guide_file"
}

# Main function
main() {
    local custom_script="${1:-}"
    
    if [[ -n "$custom_script" ]]; then
        REINSTALL_SCRIPT="$custom_script"
    fi
    
    print_title "$(msg 'prepare_reinstall')"
    
    i18n_info "starting" "Reinstall preparation"
    
    # Generate reinstall script
    generate_reinstall_script
    
    # Create guide
    create_reinstall_guide
    
    i18n_success "completed" "Reinstall preparation"
    echo ""
    echo "$(msg 'script_generated'): $REINSTALL_SCRIPT"
    echo "Guide: ${REINSTALL_SCRIPT%.sh}-GUIDE.txt"
    echo ""
    print_warning "$(msg 'warning'): Please review and customize the script before running!"
    echo ""
}

# Run main function if script is executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
