#!/usr/bin/env bash
# prepare-wizard.sh - Pre-reinstall preparation wizard
# Detects system, backs up config, generates restore script

set -Eeuo pipefail

# Load common header
if [[ -n "${SCRIPT_DIR:-}" ]] && [[ -f "$SCRIPT_DIR/utils/common-header.sh" ]]; then
    source "$SCRIPT_DIR/utils/common-header.sh"
else
    CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    TOOLKIT_ROOT="$(dirname "$CURRENT_DIR")"
    
    if [[ -f "$TOOLKIT_ROOT/utils/common.sh" ]]; then
        source "$TOOLKIT_ROOT/utils/common.sh"
    else
        echo "Error: common.sh not found"
        exit 1
    fi
    
    if [[ -f "$TOOLKIT_ROOT/utils/i18n.sh" ]]; then
        source "$TOOLKIT_ROOT/utils/i18n.sh"
    fi
fi

# Output files
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
RESTORE_SCRIPT="${HOME}/restore-config-${TIMESTAMP}.sh"
BACKUP_INFO="${HOME}/backup-info-${TIMESTAMP}.txt"

# ==================== System Detection ====================

detect_system_info() {
    i18n_info "detect_os"
    
    local os_id os_version os_name arch kernel
    
    if [[ -f /etc/os-release ]]; then
        source /etc/os-release
        os_id="$ID"
        os_version="${VERSION_ID:-unknown}"
        os_name="$PRETTY_NAME"
    else
        os_id="unknown"
        os_version="unknown"
        os_name="Unknown"
    fi
    
    arch=$(uname -m)
    kernel=$(uname -r)
    
    echo "OS_ID='$os_id'"
    echo "OS_VERSION='$os_version'"
    echo "OS_NAME='$os_name'"
    echo "ARCH='$arch'"
    echo "KERNEL='$kernel'"
}

detect_network_info() {
    i18n_info "detect_network"
    
    local primary_if primary_ip gateway dns_servers
    
    primary_if=$(get_primary_interface)
    primary_ip=$(get_primary_ip)
    
    # Get gateway
    if has_cmd ip; then
        gateway=$(ip route | grep default | awk '{print $3}' | head -1)
    else
        gateway="unknown"
    fi
    
    # Get DNS servers
    if [[ -f /etc/resolv.conf ]]; then
        dns_servers=$(grep "^nameserver" /etc/resolv.conf | awk '{print $2}' | tr '\n' ' ')
    else
        dns_servers="8.8.8.8 8.8.4.4"
    fi
    
    # Get all IPs
    local all_ips=""
    if has_cmd ip; then
        all_ips=$(ip -4 addr show | grep -oP 'inet \K[\d.]+' | grep -v '^127\.' | tr '\n' ' ')
    fi
    
    echo "PRIMARY_INTERFACE='$primary_if'"
    echo "PRIMARY_IP='$primary_ip'"
    echo "GATEWAY='$gateway'"
    echo "DNS_SERVERS='$dns_servers'"
    echo "ALL_IPS='$all_ips'"
}

detect_hostname_info() {
    local hostname_short hostname_fqdn
    
    hostname_short=$(hostname -s 2>/dev/null || hostname)
    hostname_fqdn=$(hostname -f 2>/dev/null || hostname)
    
    echo "HOSTNAME_SHORT='$hostname_short'"
    echo "HOSTNAME_FQDN='$hostname_fqdn'"
}

# ==================== Generate Restore Script ====================

generate_restore_script() {
    i18n_info "generating_script"
    
    # Collect information
    local sys_info net_info host_info
    sys_info=$(detect_system_info)
    net_info=$(detect_network_info)
    host_info=$(detect_hostname_info)
    
    eval "$sys_info"
    eval "$net_info"
    eval "$host_info"
    
    # Create restore script
    cat > "$RESTORE_SCRIPT" << 'RESTORE_EOF'
#!/usr/bin/env bash
# Configuration Restore Script
# Generated by Server Toolkit
# Run this script after OS reinstallation to restore configuration

set -Eeuo pipefail

# Colors
if [[ -t 1 ]]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' BLUE='' NC=''
fi

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# Check root
if [[ "$(id -u)" -ne 0 ]]; then
    log_error "This script must be run as root"
    exit 1
fi

RESTORE_EOF

    # Add system information
    cat >> "$RESTORE_SCRIPT" << RESTORE_EOF

# ==================== Original System Information ====================
# OS: $OS_NAME
# Architecture: $ARCH
# Kernel: $KERNEL

# ==================== Network Configuration ====================
PRIMARY_INTERFACE="$PRIMARY_INTERFACE"
PRIMARY_IP="$PRIMARY_IP"
GATEWAY="$GATEWAY"
DNS_SERVERS="$DNS_SERVERS"

# ==================== Hostname Configuration ====================
HOSTNAME_SHORT="$HOSTNAME_SHORT"
HOSTNAME_FQDN="$HOSTNAME_FQDN"

RESTORE_EOF

    # Add restore functions
    cat >> "$RESTORE_SCRIPT" << 'RESTORE_EOF'

# ==================== Restore Functions ====================

restore_network() {
    log_info "Restoring network configuration..."
    
    # Detect current interface name (may have changed)
    local current_if
    current_if=$(ip -o link show | awk -F': ' '{print $2}' | grep -v lo | head -1)
    
    if [[ -z "$current_if" ]]; then
        log_error "No network interface found"
        return 1
    fi
    
    log_info "Using interface: $current_if"
    
    # Configure IP address
    if [[ -n "$PRIMARY_IP" ]] && [[ "$PRIMARY_IP" != "127.0.0.1" ]]; then
        log_info "Configuring IP: $PRIMARY_IP"
        
        # Remove existing IPs
        ip addr flush dev "$current_if"
        
        # Add IP (assuming /24 subnet, adjust if needed)
        ip addr add "${PRIMARY_IP}/24" dev "$current_if"
        ip link set "$current_if" up
        
        log_success "IP configured: $PRIMARY_IP"
    fi
    
    # Configure gateway
    if [[ -n "$GATEWAY" ]] && [[ "$GATEWAY" != "unknown" ]]; then
        log_info "Configuring gateway: $GATEWAY"
        ip route add default via "$GATEWAY"
        log_success "Gateway configured"
    fi
    
    # Configure DNS
    if [[ -n "$DNS_SERVERS" ]]; then
        log_info "Configuring DNS servers..."
        cat > /etc/resolv.conf << DNS_EOF
# Generated by restore script
$(for dns in $DNS_SERVERS; do echo "nameserver $dns"; done)
DNS_EOF
        log_success "DNS configured"
    fi
    
    log_success "Network configuration restored"
}

restore_hostname() {
    log_info "Restoring hostname..."
    
    if [[ -n "$HOSTNAME_FQDN" ]]; then
        hostnamectl set-hostname "$HOSTNAME_FQDN"
        log_success "Hostname set to: $HOSTNAME_FQDN"
    elif [[ -n "$HOSTNAME_SHORT" ]]; then
        hostnamectl set-hostname "$HOSTNAME_SHORT"
        log_success "Hostname set to: $HOSTNAME_SHORT"
    fi
}

make_persistent() {
    log_info "Making configuration persistent..."
    
    # Detect OS
    if [[ -f /etc/os-release ]]; then
        source /etc/os-release
        local os_id="$ID"
    else
        local os_id="unknown"
    fi
    
    case "$os_id" in
        debian|ubuntu)
            log_info "Detected Debian/Ubuntu, using netplan or interfaces"
            
            if [[ -d /etc/netplan ]]; then
                # Use netplan
                cat > /etc/netplan/01-netcfg.yaml << NETPLAN_EOF
network:
  version: 2
  ethernets:
    $(ip -o link show | awk -F': ' '{print $2}' | grep -v lo | head -1):
      addresses:
        - ${PRIMARY_IP}/24
      routes:
        - to: default
          via: ${GATEWAY}
      nameservers:
        addresses: [$(echo $DNS_SERVERS | tr ' ' ', ')]
NETPLAN_EOF
                netplan apply
                log_success "Netplan configuration saved"
            else
                # Use /etc/network/interfaces
                log_warn "Please manually configure /etc/network/interfaces"
            fi
            ;;
        centos|rhel|rocky|almalinux|fedora)
            log_info "Detected RHEL-based system"
            log_warn "Please manually configure NetworkManager or network scripts"
            ;;
        *)
            log_warn "Unknown OS, please manually make configuration persistent"
            ;;
    esac
}

display_summary() {
    echo ""
    echo "=========================================="
    echo "  Configuration Restore Summary"
    echo "=========================================="
    echo ""
    echo "Hostname: $HOSTNAME_FQDN"
    echo "IP Address: $PRIMARY_IP"
    echo "Gateway: $GATEWAY"
    echo "DNS Servers: $DNS_SERVERS"
    echo ""
    echo "Next steps:"
    echo "1. Verify network connectivity: ping 8.8.8.8"
    echo "2. Test DNS resolution: ping google.com"
    echo "3. Use server-toolkit for additional configuration"
    echo ""
    echo "Run server-toolkit:"
    echo "curl -fsSL https://raw.githubusercontent.com/k3s-forge/server-toolkit/main/bootstrap.sh | bash"
    echo ""
}

# ==================== Main ====================

main() {
    echo ""
    echo "=========================================="
    echo "  Configuration Restore Wizard"
    echo "=========================================="
    echo ""
    
    log_info "Starting configuration restore..."
    
    # Restore network
    restore_network
    
    # Restore hostname
    restore_hostname
    
    # Make persistent (optional)
    read -p "Make configuration persistent? [y/N] " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        make_persistent
    fi
    
    # Display summary
    display_summary
    
    log_success "Configuration restore complete!"
}

main "$@"
RESTORE_EOF

    chmod +x "$RESTORE_SCRIPT"
    i18n_success "script_generated"
}

# ==================== Generate Backup Info ====================

generate_backup_info() {
    i18n_info "generating_report"
    
    # Collect information
    local sys_info net_info host_info
    sys_info=$(detect_system_info)
    net_info=$(detect_network_info)
    host_info=$(detect_hostname_info)
    
    eval "$sys_info"
    eval "$net_info"
    eval "$host_info"
    
    {
        echo "=========================================="
        echo "  Pre-Reinstall Backup Information"
        echo "=========================================="
        echo "Generated: $(date)"
        echo ""
        echo "=== System Information ==="
        echo "OS: $OS_NAME"
        echo "Version: $OS_VERSION"
        echo "Architecture: $ARCH"
        echo "Kernel: $KERNEL"
        echo ""
        echo "=== Network Configuration ==="
        echo "Primary Interface: $PRIMARY_INTERFACE"
        echo "Primary IP: $PRIMARY_IP"
        echo "All IPs: $ALL_IPS"
        echo "Gateway: $GATEWAY"
        echo "DNS Servers: $DNS_SERVERS"
        echo ""
        echo "=== Hostname ==="
        echo "Short: $HOSTNAME_SHORT"
        echo "FQDN: $HOSTNAME_FQDN"
        echo ""
        echo "=== Important Files to Backup ==="
        echo "- SSH keys: ~/.ssh/"
        echo "- SSH config: /etc/ssh/"
        echo "- Cron jobs: /var/spool/cron/"
        echo "- User data: /home/"
        echo "- Web data: /var/www/"
        echo "- Database: /var/lib/mysql/ or /var/lib/postgresql/"
        echo ""
        echo "=== Installed Services ==="
        if has_cmd systemctl; then
            systemctl list-units --type=service --state=running --no-pager | grep -v "^●" | head -20
        fi
        echo ""
        echo "=== Generated Files ==="
        echo "Restore script: $RESTORE_SCRIPT"
        echo "Backup info: $BACKUP_INFO"
        echo ""
        echo "=== Next Steps ==="
        echo "1. Save these files to a safe location"
        echo "2. Backup important data manually"
        echo "3. Generate OS reinstall script (option 2 in menu)"
        echo "4. After reinstall, run: bash $RESTORE_SCRIPT"
        echo ""
    } > "$BACKUP_INFO"
    
    i18n_success "report_saved"
}

# ==================== Main ====================

main() {
    print_title "$(msg 'prepare_reinstall')"
    
    i18n_info "starting" "Pre-reinstall preparation"
    
    echo ""
    i18n_info "info" "This wizard will:"
    echo "  1. $(msg 'detect_system')"
    echo "  2. $(msg 'backup_config')"
    echo "  3. Generate restore script"
    echo ""
    
    # Generate restore script
    generate_restore_script
    
    # Generate backup info
    generate_backup_info
    
    echo ""
    i18n_success "completed" "Pre-reinstall preparation"
    echo ""
    echo "$(msg 'script_generated'):"
    echo "  - Restore script: $RESTORE_SCRIPT"
    echo "  - Backup info: $BACKUP_INFO"
    echo ""
    i18n_warn "warning" "Please save these files to a safe location!"
    echo ""
    i18n_info "info" "After OS reinstall, run: bash $RESTORE_SCRIPT"
    echo ""
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
