#!/usr/bin/env bash
# reinstall-os.sh - Generate OS reinstall script with user selection
# Interactive wizard to choose OS and version

set -Eeuo pipefail

# Load common header
if [[ -n "${SCRIPT_DIR:-}" ]] && [[ -f "$SCRIPT_DIR/utils/common-header.sh" ]]; then
    source "$SCRIPT_DIR/utils/common-header.sh"
else
    CURRENT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
    TOOLKIT_ROOT="$(dirname "$CURRENT_DIR")"
    
    if [[ -f "$TOOLKIT_ROOT/utils/common.sh" ]]; then
        source "$TOOLKIT_ROOT/utils/common.sh"
    else
        echo "Error: common.sh not found"
        exit 1
    fi
    
    if [[ -f "$TOOLKIT_ROOT/utils/i18n.sh" ]]; then
        source "$TOOLKIT_ROOT/utils/i18n.sh"
    fi
fi

# Output file
TIMESTAMP=$(date +%Y%m%d_%H%M%S)
REINSTALL_SCRIPT="${HOME}/reinstall-os-${TIMESTAMP}.sh"

# ==================== OS Selection ====================

select_os() {
    echo ""
    print_separator
    case "$TOOLKIT_LANG" in
        zh)
            echo "  选择要安装的操作系统"
            ;;
        *)
            echo "  Select Operating System to Install"
            ;;
    esac
    print_separator
    echo ""
    echo "  [1] Debian"
    echo "  [2] Ubuntu"
    echo "  [3] Rocky Linux"
    echo "  [4] AlmaLinux"
    echo "  [5] Alpine Linux"
    echo "  [6] Arch Linux"
    echo "  [7] Fedora"
    echo "  [8] openSUSE Leap"
    echo "  [0] $(msg 'cancel')"
    echo ""
    
    local choice
    read -p "$(msg 'select') [0-8]: " choice
    
    case $choice in
        1) echo "debian" ;;
        2) echo "ubuntu" ;;
        3) echo "rocky" ;;
        4) echo "alma" ;;
        5) echo "alpine" ;;
        6) echo "arch" ;;
        7) echo "fedora" ;;
        8) echo "opensuse" ;;
        0) echo "cancel" ;;
        *) echo "invalid" ;;
    esac
}

select_debian_version() {
    echo ""
    case "$TOOLKIT_LANG" in
        zh) echo "选择 Debian 版本:" ;;
        *) echo "Select Debian version:" ;;
    esac
    echo "  [1] Debian 11 (Bullseye)"
    echo "  [2] Debian 12 (Bookworm)"
    echo ""
    
    local choice
    read -p "$(msg 'select') [1-2]: " choice
    
    case $choice in
        1) echo "11" ;;
        2) echo "12" ;;
        *) echo "12" ;;
    esac
}

select_ubuntu_version() {
    echo ""
    case "$TOOLKIT_LANG" in
        zh) echo "选择 Ubuntu 版本:" ;;
        *) echo "Select Ubuntu version:" ;;
    esac
    echo "  [1] Ubuntu 20.04 LTS (Focal)"
    echo "  [2] Ubuntu 22.04 LTS (Jammy)"
    echo "  [3] Ubuntu 24.04 LTS (Noble)"
    echo ""
    
    local choice
    read -p "$(msg 'select') [1-3]: " choice
    
    case $choice in
        1) echo "20.04" ;;
        2) echo "22.04" ;;
        3) echo "24.04" ;;
        *) echo "22.04" ;;
    esac
}

select_rocky_version() {
    echo ""
    case "$TOOLKIT_LANG" in
        zh) echo "选择 Rocky Linux 版本:" ;;
        *) echo "Select Rocky Linux version:" ;;
    esac
    echo "  [1] Rocky Linux 8"
    echo "  [2] Rocky Linux 9"
    echo ""
    
    local choice
    read -p "$(msg 'select') [1-2]: " choice
    
    case $choice in
        1) echo "8" ;;
        2) echo "9" ;;
        *) echo "9" ;;
    esac
}

select_alma_version() {
    echo ""
    case "$TOOLKIT_LANG" in
        zh) echo "选择 AlmaLinux 版本:" ;;
        *) echo "Select AlmaLinux version:" ;;
    esac
    echo "  [1] AlmaLinux 8"
    echo "  [2] AlmaLinux 9"
    echo ""
    
    local choice
    read -p "$(msg 'select') [1-2]: " choice
    
    case $choice in
        1) echo "8" ;;
        2) echo "9" ;;
        *) echo "9" ;;
    esac
}

select_fedora_version() {
    echo ""
    case "$TOOLKIT_LANG" in
        zh) echo "选择 Fedora 版本:" ;;
        *) echo "Select Fedora version:" ;;
    esac
    echo "  [1] Fedora 39"
    echo "  [2] Fedora 40"
    echo ""
    
    local choice
    read -p "$(msg 'select') [1-2]: " choice
    
    case $choice in
        1) echo "39" ;;
        2) echo "40" ;;
        *) echo "40" ;;
    esac
}

# ==================== Generate Script ====================

generate_reinstall_script() {
    local os_name="$1"
    local os_version="$2"
    
    i18n_info "generating_script"
    
    # Create reinstall script
    cat > "$REINSTALL_SCRIPT" << 'REINSTALL_EOF'
#!/usr/bin/env bash
# OS Reinstall Script
# Generated by Server Toolkit
# WARNING: This will ERASE ALL DATA on the system disk!

set -Eeuo pipefail

# Colors
if [[ -t 1 ]]; then
    RED='\033[0;31m'
    GREEN='\033[0;32m'
    YELLOW='\033[1;33m'
    BLUE='\033[0;34m'
    NC='\033[0m'
else
    RED='' GREEN='' YELLOW='' BLUE='' NC=''
fi

log_info() { echo -e "${BLUE}[INFO]${NC} $*"; }
log_success() { echo -e "${GREEN}[SUCCESS]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

REINSTALL_EOF

    # Add OS information
    cat >> "$REINSTALL_SCRIPT" << REINSTALL_EOF

# ==================== Target OS Configuration ====================
TARGET_OS="$os_name"
TARGET_VERSION="$os_version"

REINSTALL_EOF

    # Add reinstall functions
    cat >> "$REINSTALL_SCRIPT" << 'REINSTALL_EOF'

# ==================== Safety Checks ====================

check_root() {
    if [[ "$(id -u)" -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

check_network() {
    log_info "Checking network connectivity..."
    if ! ping -c 1 8.8.8.8 >/dev/null 2>&1; then
        log_error "No network connectivity"
        exit 1
    fi
    log_success "Network OK"
}

confirm_reinstall() {
    echo ""
    log_warn "=========================================="
    log_warn "  WARNING: SYSTEM REINSTALL"
    log_warn "=========================================="
    echo ""
    log_warn "This will:"
    log_warn "  - ERASE ALL DATA on the system disk"
    log_warn "  - Install $TARGET_OS $TARGET_VERSION"
    log_warn "  - Reboot the system automatically"
    echo ""
    log_warn "Make sure you have:"
    log_warn "  ✓ Backed up all important data"
    log_warn "  ✓ Saved network configuration"
    log_warn "  ✓ Access to server console (IPMI/KVM)"
    echo ""
    
    read -p "Type 'YES' to continue: " confirm
    if [[ "$confirm" != "YES" ]]; then
        log_info "Reinstall cancelled"
        exit 0
    fi
    
    echo ""
    read -p "Type 'REINSTALL' to confirm: " confirm2
    if [[ "$confirm2" != "REINSTALL" ]]; then
        log_error "Confirmation failed"
        exit 1
    fi
}

# ==================== Download Reinstall Tool ====================

download_reinstall_tool() {
    log_info "Downloading reinstall tool..."
    
    local reinstall_url="https://raw.githubusercontent.com/bin456789/reinstall/main/reinstall.sh"
    local temp_file="/tmp/reinstall-tool.sh"
    
    if command -v curl >/dev/null 2>&1; then
        curl -fsSL "$reinstall_url" -o "$temp_file"
    elif command -v wget >/dev/null 2>&1; then
        wget -q "$reinstall_url" -O "$temp_file"
    else
        log_error "Neither curl nor wget is available"
        exit 1
    fi
    
    chmod +x "$temp_file"
    log_success "Reinstall tool downloaded"
    
    echo "$temp_file"
}

# ==================== Execute Reinstall ====================

execute_reinstall() {
    local reinstall_tool="$1"
    
    log_info "Starting OS reinstall..."
    log_info "Target: $TARGET_OS $TARGET_VERSION"
    echo ""
    
    # Execute reinstall
    if [[ -n "$TARGET_VERSION" ]] && [[ "$TARGET_VERSION" != "latest" ]]; then
        bash "$reinstall_tool" "$TARGET_OS" "$TARGET_VERSION"
    else
        bash "$reinstall_tool" "$TARGET_OS"
    fi
}

# ==================== Main ====================

main() {
    echo ""
    echo "=========================================="
    echo "  OS Reinstall Script"
    echo "=========================================="
    echo ""
    echo "Target OS: $TARGET_OS $TARGET_VERSION"
    echo ""
    
    # Safety checks
    check_root
    check_network
    
    # Confirm
    confirm_reinstall
    
    # Download tool
    local reinstall_tool
    reinstall_tool=$(download_reinstall_tool)
    
    # Execute
    execute_reinstall "$reinstall_tool"
    
    # This line may not be reached if system reboots
    log_success "Reinstall initiated"
}

main "$@"
REINSTALL_EOF

    chmod +x "$REINSTALL_SCRIPT"
    i18n_success "script_generated"
}

# ==================== Main ====================

main() {
    print_title "$(msg 'generate_script')"
    
    # Select OS
    local os_name
    os_name=$(select_os)
    
    if [[ "$os_name" == "cancel" ]]; then
        i18n_info "info" "Cancelled"
        exit 0
    elif [[ "$os_name" == "invalid" ]]; then
        i18n_error "error" "Invalid choice"
        exit 1
    fi
    
    # Select version
    local os_version="latest"
    case "$os_name" in
        debian)
            os_version=$(select_debian_version)
            ;;
        ubuntu)
            os_version=$(select_ubuntu_version)
            ;;
        rocky)
            os_version=$(select_rocky_version)
            ;;
        alma)
            os_version=$(select_alma_version)
            ;;
        fedora)
            os_version=$(select_fedora_version)
            ;;
        alpine|arch|opensuse)
            os_version="latest"
            ;;
    esac
    
    # Confirm selection
    echo ""
    i18n_info "info" "Selected: $os_name $os_version"
    echo ""
    read -p "$(msg 'confirm')? [y/N] " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        i18n_info "info" "Cancelled"
        exit 0
    fi
    
    # Generate script
    generate_reinstall_script "$os_name" "$os_version"
    
    echo ""
    i18n_success "completed" "OS reinstall script generation"
    echo ""
    echo "$(msg 'script_generated'): $REINSTALL_SCRIPT"
    echo ""
    i18n_warn "warning" "Review the script before running!"
    echo ""
    i18n_info "info" "To execute: bash $REINSTALL_SCRIPT"
    echo ""
}

# Run if executed directly
if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
    main "$@"
fi
